omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/onig_sys-69.8.1/build.rs. Dependencies:
    cc-1.0.79
    pkg-config-0.3.26'''

[extra_mapped_srcs]

[platform_fixup]
